server:
  port: 10000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: user-wechat-service
  datasource:
    data-username: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/user-wechat?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true